-- Case 1
SELECT * FROM TBLORDERS WHERE CUSTOMERID = 'MAGAA'

-- Case 2
SELECT CUSTOMERID, COMPANYNAME, CONTACTNAME, CONTACTTITLE FROM TBLCUSTOMERS WHERE CONTACTTITLE != 'Sales Associate'

-- Case 3
SELECT TBLCUSTOMERS.CUSTOMERID, TBLCUSTOMERS.COMPANYNAME, TBLPRODUCTS.PRODUCTID, TBLPRODUCTS.PRODUCTNAME, TBLPRODUCTS.ENGLISHNAME 
FROM TBLORDERDETAILS
left join TBLORDERS on TBLORDERDETAILS.ORDERID = TBLORDERS.ORDERID
left join TBLCUSTOMERS on TBLORDERS.CUSTOMERID = TBLCUSTOMERS.CUSTOMERID
left join TBLPRODUCTS on TBLORDERDETAILS.PRODUCTID = TBLPRODUCTS.PRODUCTID 
WHERE TBLPRODUCTS.ENGLISHNAME like '%Chocolate%'

-- Case 4
SELECT TBLCUSTOMERS.CUSTOMERID, TBLCUSTOMERS.COMPANYNAME, TBLORDERS.SHIPCOUNTRY, TBLPRODUCTS.PRODUCTID, TBLPRODUCTS.PRODUCTNAME, TBLPRODUCTS.ENGLISHNAME
FROM TBLORDERDETAILS
left join TBLORDERS on TBLORDERDETAILS.ORDERID = TBLORDERS.ORDERID
left join TBLCUSTOMERS on TBLORDERS.CUSTOMERID = TBLCUSTOMERS.CUSTOMERID
left join TBLPRODUCTS on TBLORDERDETAILS.PRODUCTID = TBLPRODUCTS.PRODUCTID
WHERE TBLORDERS.SHIPCOUNTRY = 'USA' OR TBLORDERS.SHIPCOUNTRY = 'Italy'

-- Case 5
SELECT TBLORDERDETAILS.ORDERID, TBLORDERDETAILS.PRODUCTID, TBLPRODUCTS.PRODUCTNAME, TBLPRODUCTS.UNITPRICE, TBLORDERDETAILS.QUANTITY, TBLORDERDETAILS.DISCOUNT,
TBLPRODUCTS.UNITPRICE*TBLORDERDETAILS.QUANTITY*(1-TBLORDERDETAILS.DISCOUNT) AS 'TotalPrice'
FROM TBLORDERDETAILS
left join TBLPRODUCTS on TBLORDERDETAILS.PRODUCTID = TBLPRODUCTS.PRODUCTID

-- Case 6
SELECT CATEGORYID, COUNT(*) AS TotalProducts
FROM TBLPRODUCTS
GROUP BY CATEGORYID
ORDER BY TotalProducts ASC

-- Case 7
SELECT COUNTRY, CITY, COUNT(CITY) AS TotalCustomers
FROM TBLCUSTOMERS
GROUP BY CITY, COUNTRY

-- Case 8
SELECT ORDERID, ORDERDATE, REQUIREDDATE, SHIPPEDDATE
FROM TBLORDERS
WHERE REQUIREDDATE < SHIPPEDDATE